### ISSUE TITLE
Slide-left and slide-right transitions not working in Android

### ISSUE THREAD

**Issue by KavyaS08** [mendix/MobileFeatures#15] opened 2018-10-29 10:10 UTC
Slide-left and slide-right transitions not working in Android. iOS perfectly working fine. Instead of slide it is looking a flash of page.

**Comment by jseremba** [comment] 2018-10-29 13:03
Hello @KavyaS08 
Thanks for raising this issue. We will look in it and get back to you as soon as we can.

**Comment by jseremba** [comment] 2018-10-31 09:35
Hello @KavyaS08 
We are having trouble reproducing the issue, kindly attach a sample test project and android version to help us getting around with it.

**Comment by aishjam** [comment] 2018-12-14 07:14
Hi @jseremba 

I have a similar issue and this is reproducible in a particular case. This doesn't work on those buttons which calls a microflow and under Microflow settings > Show progress bar is set to 'Blocking' and have opted 'No' for Enable Spinner.

Please find the attached sample app and provide a solution on this ASAP
[TestApp.zip](https://github.com/mendix/MobileFeatures/files/2678973/TestApp.zip)

Thanks,
Aishwarya

**Comment by JelteMX** [comment] 2019-02-06 15:54
We have been working on some tickets that regard this issue. Can you please test [this](https://github.com/mendix/MobileFeatures/raw/bugfix/transitions_buttons/dist/MobileFeatures.mpk) version and see if the issue is resolved?

**Comment by JelteMX** [comment] 2019-02-13 10:13
This issue has been resolved in [version 1.4.0](https://github.com/mendix/MobileFeatures/releases/tag/v1.4.0) and is updated in the AppStore. Closing the question

**Closed by JelteMX** 2019-02-13 10:13 UTC
