### ISSUE TITLE
Transition classes not working in android devices

### ISSUE THREAD

**Issue by aishjam** [mendix/MobileFeatures#17] opened 2018-12-17 05:18 UTC
Hi 

I have an issue where slide-left and slide-right classes doesn't work in android devices. This happens only in particular case. This doesn't work on those buttons which calls a microflow and under Microflow settings > Show progress bar is set to 'Blocking' and have opted 'No' for Enable Spinner.

Please find the attached sample app and provide a solution on this ASAP
[TestApp.zip](https://github.com/mendix/MobileFeatures/files/2684532/TestApp.zip)

Thanks,
Aishwarya

**Comment by JelteMX** [comment] 2019-02-06 15:54
We have been working on some tickets that regard this issue. Can you please test [this](https://github.com/mendix/MobileFeatures/raw/bugfix/transitions_buttons/dist/MobileFeatures.mpk) version and see if the issue is resolved?

**Comment by JelteMX** [comment] 2019-02-13 10:13
This issue has been resolved in [version 1.4.0](https://github.com/mendix/MobileFeatures/releases/tag/v1.4.0) and is updated in the AppStore. Closing the question

**Closed by JelteMX** 2019-02-13 10:13 UTC
